In [57]:
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn import preprocessing
from sklearn import metrics
import numpy as np
#from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve, auc,precision_score, accuracy_score, recall_score, f1_score
import matplotlib.pyplot as plt
import pickle

In [58]:
path = "C:/Users/61487/Desktop/CompanyNGO/companyandngo/Data/Datasets/"
Au_dataset = pd.read_csv(path + 'AUFinal.csv')
Au_dataset
#Date =  pd.to_datetime(Au_dataset['Date'])

,Date,AORD_monthly_adj_closed,10Y_Bond_Yields,3M_Bond_Yields,3M_10Y_Treasury_Spread,Unemployment_Rate,Recession,Recession_within_6M,Recession_within_12M,Recession_within_24M
0,02/01/20,6511.500000,0.98,0.89,0.09,5.097311,0,0,0,0
1,01/01/20,7121.200195,1.15,0.89,0.26,5.290084,0,0,0,0
2,12/01/19,6802.399902,1.20,0.90,0.30,5.062629,0,0,0,0
3,11/01/19,6948.000000,1.15,0.91,0.24,5.171340,0,0,0,0
4,10/01/19,6772.899902,1.03,0.88,0.15,5.302068,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...
422,12/01/84,726.099976,13.40,12.34,1.06,8.520384,0,0,1,0
423,11/01/84,749.000000,13.25,11.26,1.99,8.679548,0,0,1,0
424,10/01/84,749.000000,13.20,11.17,2.03,8.695913,0,0,1,0
425,09/01/84,733.500000,13.10,10.53,2.57,8.735682,0,0,1,0
426,08/01/84,733.200012,12.80,11.56,1.24,8.829420,0,0,1,1

In [61]:
features = ['AORD_monthly_adj_closed', '10Y_Bond_Yields', '3M_Bond_Yields',
                         '3M_10Y_Treasury_Spread', 'Unemployment_Rate', 'Recession',
                         'Recession_within_6M','Recession_within_12M', 'Recession_within_24M']

#date = Au_dataset['Date']
recession_dataset  = Au_dataset[features]
Recession_6months  = Au_dataset['Recession_within_6M']

Recession_12months =  Au_dataset['Recession_within_12M']

Recession_24months = Au_dataset['Recession_within_24M']

In [62]:
Model_gb = GaussianNB()
#predicting for 6months
X_train, X_test, y_train, y_test = train_test_split(recession_dataset.iloc[:,0:3],Recession_6months,test_size=0.3,random_state=350)
Model_gb.fit(X_train, y_train)
Prediction_for_6months = Model_gb.predict(X_test)
Prediction_for_6months

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
      dtype=int64)

In [25]:

#Evaluationg Model
print("Accuracy:",metrics.accuracy_score(y_test, Prediction_for_6months))
recession_predicted_6 = pd.DataFrame(Model_gb.predict_proba(X_test)[:,1])
ROC_AUC=roc_auc_score(y_test,recession_predicted_6)
ROC_AUC
recession_predicted_6mo = pd.DataFrame(recession_predicted_6)
recession_predicted_6mo

Accuracy: 0.5348837209302325

            0
0    0.522611
1    0.374411
2    0.330238
3    0.333456
4    0.341717
..        ...
124  0.361936
125  0.872503
126  0.415194
127  0.352458
128  0.835555

[129 rows x 1 columns]

In [27]:
#prediction for recession 12 months
X_train, X_test, y_train, y_test = train_test_split(recession_dataset.iloc[:,1:3],Recession_12months, test_size=0.30,random_state=350)
Model_gb.fit(X_train, y_train)
Prediction_for_12months= Model_gb.predict(X_test)
Prediction_for_12months
#Evaluationg Model
print("Accuracy:",metrics.accuracy_score(y_test, Prediction_for_12months))
recession_predicted_12 = pd.DataFrame(Model_gb.predict_proba(X_test)[:,1])
ROC_AUC=roc_auc_score(y_test,recession_predicted_12)
ROC_AUC
recession_predicted_12 = pd.DataFrame(recession_predicted_12)
recession_predicted_12

Accuracy: 0.5271317829457365

            0
0    0.521245
1    0.347071
2    0.352403
3    0.359087
4    0.355592
..        ...
124  0.394058
125  0.770043
126  0.438015
127  0.346771
128  0.730227

[129 rows x 1 columns]

In [29]:

#prediction for recession 2 years
X_train, X_test, y_train, y_test = train_test_split(recession_dataset.iloc[:,1:5],Recession_24months, test_size=0.30,random_state=350)
Model_gb.fit(X_train, y_train)
Prediction_for_24months= Model_gb.predict(X_test)
print(Prediction_for_24months)
#Evaluationg Model
print("Accuracy:",metrics.accuracy_score(y_test, Prediction_for_24months))
recession_predicted_24 = pd.DataFrame(Model_gb.predict_proba(X_test)[:,1])
ROC_AUC=roc_auc_score(y_test,recession_predicted_24)
ROC_AUC
recession_predicted_24

[0 0 0 0 1 0 0 0 0 1 0 1 1 0 0 0 1 0 1 1 1 1 0 0 0 1 0 1 1 1 0 0 0 0 1 1 1
 0 1 0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 1 1 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0 1 0
 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 1 0 1 0 0 1 0 0 1 0
 0 1 0 0 1 0 1 0 0 1 1 1 0 1 0 0 0 0]
Accuracy: 0.689922480620155

            0
0    0.197899
1    0.476888
2    0.423819
3    0.417766
4    0.613247
..        ...
124  0.681344
125  0.184590
126  0.360267
127  0.462490
128  0.367078

[129 rows x 1 columns]

In [63]:

recession_probabilities = pd.concat([recession_predicted_6mo,recession_predicted_12,recession_predicted_24 ],axis =1)
recession_probabilities.columns = ['Recession probability in 6 months','Recession probability in 12 months','Recession probability in 24 months']
recession_probabilities.head(20)
#y_axis = ['Recession probability in 6 months','Recession probability in 12 months','Recession probability in 24 months']

#recession_probabilities.plot('Date', y_axis,figsize =(20,4))

,Recession probability in 6 months,Recession probability in 12 months,Recession probability in 24 months
0,0.522611,0.521245,0.197899
1,0.374411,0.347071,0.476888
2,0.330238,0.352403,0.423819
3,0.333456,0.359087,0.417766
4,0.341717,0.355592,0.613247
5,0.349832,0.345955,0.480062
6,0.611066,0.576237,0.152704
7,0.369699,0.347100,0.459892
8,0.336643,0.347420,0.483365
9,0.365509,0.346341,0.520387
10,0.749263,0.672435,0.120287
11,0.379512,0.379194,0.776289
12,0.381216,0.410840,0.580154
13,0.655847,0.613941,0.121495
14,0.332855,0.356415,0.414745
15,0.355420,0.382409,0.429147
16,0.336757,0.356665,0.542527
17,0.393547,0.352812,0.427061
18,0.345800,0.344353,0.507257
19,0.361524,0.363373,0.667198